### PR TITLE
Generate RTFNotes from Notes during build process

### PR DESCRIPTION
**Pull request by asherber**
I basically hooked into the class that injects the `HashURL` so that it also injects `RTFNotes`. And the design is a little more modular now, so we can more easily inject other elements in the future, if needed. 

I confirmed locally that dist files built in this branch differ from master only by the presence of `RTFNotes` (where appropriate) and the lack of whitespace mangling in `plugindef`. 

I'm happy for any suggestions or questions.

### CODE REVIEW

**Comment by asherber** [comment]
(I'll submit a separate PR for the library function I'm working on to display `RTFNotes` with the new text editor control.)

**Comment by asherber** [comment]
Oh, I forgot to add pandoc to the GitHub runner. That'll be the next commit.

**Comment by rpatters1** [comment]
This PR can't be merged at the moment.

**Comment by asherber** [comment]
Fixed

**Review by rpatters1 — APPROVED** [review]
looks good to me

**Pull request merged**
