### PR TITLE
Update rest_offsets.lua

### PR DESCRIPTION
**Pull request by cv-on-hub**
The `/dist` version of this script is still faulty, damaging the perceived reliability of the repository. This script works properly WITHOUT MIXIN until those bugs are fixed.

### CODE REVIEW

**Comment by ThistleSifter** [comment]
Check the `/dist` version again, the issue should hopefully be fixed now.

**Comment by cv-on-hub** [comment]
Sorry, but both `rest_offsets.lua` and `layers_swap_selective.lua` both fail (freshly downloaded today). Oddly they have different problems. `offsets` seems to lose all values in the global config variable and won't retain window position. `layers` just doesn't work.

**Comment by cv-on-hub** [comment]
Sorry - those errors the wrong way around. and in `rest_offsets`, the problem is at line 8583:
bad argument #1 to ‘abs’ (number expected, got nil)
This is in the main program, examining `config.layer` (integer) so that value isn’t being retained.

**Comment by ThistleSifter** [comment]
Looking into this now.

**Comment by cv-on-hub** [comment]
Script now functional. Closing this PR.

**Pull request closed without merging**
