### PR TITLE
Update cuenotes_create.lua

### PR DESCRIPTION
**Pull request by cv-on-hub**
Sorry about the multiple submissions yesterday. Couldn't get indents to align properly in GitHub. This version ahould be OK now.

### CODE REVIEW

**Comment by ThistleSifter** [comment]
I was just curious as to why you've opted not to use mixins here. Is it personal preference or is there an issue that needs to be resolved?

**Comment by cv-on-hub** [comment]
> you've opted not to use mixins here.

This is an older script that pre-dated my `mixin` use, and of the four dialog windows only one was complex enough to justify the changeover. Also, I found that new problem with RGPLua 0.65 right at the time of lodgement and thought it better to wait until it was fully sorted!

**Review by Nick-Mazuk — APPROVED** [review]

**Comment by rpatters1** [comment]
Is this ready to go? It looks okay to me.

**Comment by cv-on-hub** [comment]
> Is this ready to go? It looks okay to me.

It is ready to go.

**Pull request merged**
