### PR TITLE
re-create notes_tie.lua

### PR DESCRIPTION
**Pull request by cv-on-hub**
Moving the script to the correct location. (/src).

### CODE REVIEW

**Comment by cv-on-hub** [comment]
PS: as soon as this lot is cleared I'll rebuild my GitHub connection. Confusion has developed between Git and the script editor.

**Comment by Nick-Mazuk** [comment]
Same comment here about rebasing as from the comment in the other PR about rebasing.

**Comment by rpatters1** [comment]
I also noticed an issue, which is that you can't iterate from `StartStaff` to `EndStaff` on a region. The staff numbers can be in any order. Instead, iterate from `StartSlot` to `EndSlot` and then use `CalcStaffNumber` to get the staff number inside the loop.

**Comment by cv-on-hub** [comment]
Indeed - which is the workaround I used in all the Staff_Explode scripts. Will fix in the next iteration of notes_tie once my Desktop GitHub stops spewing redundant copies of old scripts.

**Review by Nick-Mazuk — APPROVED** [review]
LGTM

**Pull request merged**
