### PR TITLE
Update hairpin_creator.lua

### PR DESCRIPTION
**Pull request by cv-on-hub**
re-submitting again for GroupName inclusion

### CODE REVIEW

**Comment by rpatters1** [comment]
It looks to me like your changes are already merged. The only thing that's changed here is the file date.

**Comment by Nick-Mazuk** [comment]
Perhaps you're accidentally on an outdated version of the repo? Perhaps try pulling from the main repo?

```
git pull upstream master
```

To be honest, I'm not entirely sure what's going on here.

**Comment by Nick-Mazuk** [comment]
> It looks to me like your changes are already merged. The only thing that's changed here is the file date.

FYI, the changes don't seem to be in the main repo. But I agree, other than the date there's nothing in the diff.

https://github.com/finale-lua/lua-scripts/blob/master/src/hairpin_creator.lua

**Comment by cv-on-hub** [comment]
I'll try to consolidate all my local branches and do an upstream master pull. Meanwhile closing this PR.

**Pull request closed without merging**
