### PR TITLE
Update ostinato_maker.lua

### PR DESCRIPTION
**Pull request by cv-on-hub**
Couldn't work out how to "resolve" the previous PR so started fresh. Converted all global variables to local, assorted minor improvements. Now shouldn't require any LINT warnings.

### CODE REVIEW

**Comment by cv-on-hub** [comment]
I don't understand why this is still showing `global` conflicts when those variables are no longer part of the revised script.

**Comment by asherber** [comment]
Let me take a look.

**Comment by asherber** [comment]
Your branch was not based on upstream/master -- it was based on another commit. So GH was seeing that you made some changes (from that commit) and upstream/master had different changes.

I rebased your branch on upstream/master and force pushed to get rid of the conflicts.

**Comment by cv-on-hub** [comment]
> I rebased your branch on upstream/master and force pushed to get rid of the conflicts.

I thought that's what I did but clearly not! Thanks for sorting it out. Having the same problem with `staff_explode` but will persevere.

**Comment by asherber** [comment]
Do a `git fetch --all` first. Your copy of upstream is not up to date -- you've got upstream/master at f017, from 1/27, and the current head commit is 68302, from today.

**Pull request merged**
