### PR TITLE
Create rest_minimiser.lua

### PR DESCRIPTION
**Pull request by cv-on-hub**
New script to delete any rests in the selection that serve no musical function.

### CODE REVIEW

**Comment by cv-on-hub** [comment]
> Have you looked at `FCNoteEntryCell.ReduceEntries`?

I didn't know such a thing existed, and see that you just created it in RGP 0.68. Could reduce this script to a couple of lines! Thanks Robert ... will examine and simplify. (I had also never really noticed `FCNoteEntryCell` before - looks incredibly useful).

**Comment by rpatters1** [comment]
The [version history](https://robertgpatterson.com/-fininfo/-rgplua/vershist.html) is usually worth perusing after each release. :-)

**Comment by rpatters1** [comment]
FWIW: `FCNoteEntryCell` is what `eachentry` and `eachentrysaved` use under the covers. You might find it interesting to look at the [how those functions work](https://github.com/finale-lua/lua-source/blob/master/built-in-functions/rgplua_built_in_functions.lua).

We also added a `FCXNoteEntryCell` to the `mixin` library that allows you to cherry pick entries from an `eachentry` loop for later processing without risk of crashing Finale. (The built-in version has that risk.)

**Comment by cv-on-hub** [comment]
> There is a lot of overlap with this script

This is an understatement of delightfully mammoth proportions. That script is gone and replaced with 30 terse line under a new name: `rhythm_reducer.lua`.

**Pull request merged**
