### PR TITLE
Add script tp change meters

### PR DESCRIPTION
**Pull request by Nick-Mazuk**
Nothing more to add. Title says it all.

### CODE REVIEW

**Review by rpatters1 — COMMENTED** [review]
I just recently discovered you can replace 

```lua
        local allMeasures = finale.FCMeasures()
        allMeasures:LoadAll()
        for m in each(allMeasures) do
```
with

```lua
for m in loadall(finale.Measures()) do
```

It's been there all along in JW Lua. (There's also a similar `loadallforregion` built-in func.)

Also, don't the compound meters need a display-as as well?

**Review by rpatters1 — COMMENTED** [review]
Also, if the `AdditionalUndoText` is identical to `AdditionalMenuOptions` then you can omit the undo text block.

**Comment by Nick-Mazuk** [comment]
That's an awesome JW Lua feature! Will remove a ton of code.

I don't believe the compound meters need a display-as. I've been using this for years and haven't had any issues with compound meters as is.



> Also, if the `AdditionalUndoText` is identical to `AdditionalMenuOptions` then you can omit the undo text block.

Good to know. Will remove it.

**Comment by rpatters1** [comment]
Yes, on further reflection you don't need the display time sig. That would be for compound meters.

`loadallinregion` only works for collections that have a `LoadAllInRegion` method. (And `loadall` only works for collections with `LoadAll`.) I don't think `loadallinregion` will work in the script here, more's the pity, but `loadall` will.

**Pull request merged**
