### PR TITLE
Create gracenote_slash.lua

### PR DESCRIPTION
**Pull request by cv-on-hub**
New script that duplicates Jari Williamsson's original JWGraceNoteSlash plug-in. **Happy New Year!**

### CODE REVIEW

**Comment by ThistleSifter** [comment]
Could you move the call to `SetTypeMeasurement` so that it comes before `SetMeasurement`? ie `SetTypeMeasurement():SetMeasurement(config[name])`

I've been brainstorming some solutions for #389 and if I end up going with my current idea, the order will make a difference.

(Incidentally, I would have written them in the order I suggested above regardless because `SetTypeMeasurement` is a setup method, and I think in general it's better form (and safer) to compete setup before feeding in actual data.)

**Comment by cv-on-hub** [comment]
> Could you move the call to `SetTypeMeasurement`

Sure - easy to do. Doesn't (for now, naturally) alter the rounding error problem!

**Comment by rpatters1** [comment]
This looks okay to me, but should we not hold off until the rounding problem is fixed?

**Comment by cv-on-hub** [comment]
> hold off until the rounding problem is fixed?

Agreed.

**Comment by cv-on-hub** [comment]
As Robert pointed out in Issue #394 the majority of parameter measurements should be integer EVPUs, so in this script only the EFIX value for LineWidth demands decimal EVPUs. In this revision I've returned the other parameters to `TypeMeasurementInteger`. Not sure if the discrepancy in unit accuracy needs visual clarification for the user.

**Comment by ThistleSifter** [comment]
Finale doesn't offer any visual distinction between the different types in its dialogs. Not that I think that's good UI (it's confusing when entered values are rounded in seemingly random ways), but if you were to just leave it, at least it would be consistent.

If you were to distinguish them it would probably be with a text label of some sort, although I'm not sure what a clean solution would look like without confusing the user further ("What on earth is an EFIX??? I just want slashes on my grace notes, why do I need to know all this extra stuff?").

**Comment by cv-on-hub** [comment]
Thanks for the response @ThistleSifter - yes the UI is muddled. **Smart Shape Options...** for instance has integers and decimals alongside each other with the actual stored (integer) value only confirmed when the dialog reopens. In which case I'll stick to the new version with `LineWidth` decimal and the rest integer, just like papa Finale.

**Comment by rpatters1** [comment]
Is this PR ready to go?

**Comment by cv-on-hub** [comment]
> Is this PR ready to go?

I believe so!

**Pull request merged**
