### PR TITLE
Add `SetMeasurement` to `FCMString`

### PR DESCRIPTION
**Pull request by ThistleSifter**
Fixes an issue in `FCString` and `FCCtrlEdit` on Mac with displayed numbers being truncated (not even rounded...) at 2 decimal places. Since `FCMCtrlEdit` and `FCXCtrlMeasurementEdit` both use `FCMString` internally, this PR will fix the issues there too.

As with `GetMeasurement`, this once again emulates the behaviour that `FCCtrlEdit` has on Windows while the window is showing. All units display to 5 decimal places (for Picas, the whole number after the 'p' counts as the first decimal place).

For invalid measurement units, the Windows `FCCtrlEdit` behaviour is to just display the raw number, in other words as if it was EVPUs. The `FCString` behaviour was to set a blank string. I've gone with the Windows `FCCtrlEdit` behaviour but I'm happy to take suggestions.

I ran out of time this morning to write up a pretty test script. If you need one, I might be able to do it later today.

@rpatters1 @cv-on-hub

### CODE REVIEW

**Comment by cv-on-hub** [comment]
I don't know how many other contortions could be tested but this revision does everything that I want with strong accuracy to 5 decimal places. It also nicely trims the display of trailing zeroes.

**Comment by rpatters1** [comment]
Let me know if I should merge. I am cool with it when you are.

**Comment by ThistleSifter** [comment]
Go for it.

**Comment by rpatters1** [comment]
It looks like this PR introduced some lint errors on `GetRangeMeasurement10000th`. Specifically, it looks as though `minimum` and `maximum` were omitted from the argument list of the function.

**Pull request merged**
