### PR TITLE
Create slur_selection.lua

### PR DESCRIPTION
**Pull request by cv-on-hub**
Create slurs across the current selection. A little idea that became bigger in the realisation, addressing the surprising absence of slur-related scripts in the repo.

### CODE REVIEW

**Comment by jwink75** [comment]
Hey Carl… I have a very fancy slur engine that can submit… Meant to do it after the last batch was accepted but I’ve been swamped. Anyways, it does a LOT of things, including slur over a selection… But we’re probably duplicating work!

**Comment by cv-on-hub** [comment]
> I have a very fancy slur engine that can submit

Yes Jacob - it was your post to the FaceBook group that got me thinking about slurs. This script is just an access point for `smartshape.lua` and it would be great if your routines can get added in there.

**Comment by cv-on-hub** [comment]
Hey @jwink75 ... if you have any finished scripts containing routines that could populate `smartshape.lua` I can help start the extraction process.

**Comment by jwink75** [comment]
Extraction?

I do have one called ’Slur Wizard’. I think I may have found a few more kinks in it after using it as part of JetStream, so let me try to address that and then post...

**Comment by rpatters1** [comment]
Is this ready to go? It looks okay to me.

**Comment by cv-on-hub** [comment]
> Is this ready to go? It looks okay to me.

It's ready to go. If Jacob's work adds extra functionality to `smartshape.lua` this script will still use just the original one function.

**Pull request merged**
