### PR TITLE
Tweaks to harp pedal wizard

### PR DESCRIPTION
**Pull request by jwink75**
- Improved pentatonic and whole tone scale algorithms
- Replaced one internal function with a library function
- Added locrian scale

### CODE REVIEW

**Review by rpatters1 — COMMENTED** [review]
B-but locrian has no sol!

(I have no issues with this code. I'll let @Nick-Mazuk  comment first.)

**Comment by jwink75** [comment]
> 

I asked Jason whether he could name me a single piece actually written in locrian off the top of his head... Nope! Still, it was easy enough to add!

**Comment by rpatters1** [comment]
FWIW: I'm still seeing a ton of lint errors on the harp_pedal script. Mostly undefined globals, but also the use of `NULL` when you should be using `nil`. Not sure if you have fixed them.

The tie script looks great.

**Comment by jwink75** [comment]
I thought I had fixed the null thing, but I have definitely been having issues with GitHub, so I’ll take another look. 

As for the globals… it’s there I way I can check the lint errors on GitHub?

**Comment by rpatters1** [comment]
I use Visual Studio Code with the recommended settings.

**Comment by jwink75** [comment]
Is there a way to see lint errors on ZeroBrane Studio?

**Comment by jwink75** [comment]
Found those NULLs you mentioned. They are all replaced with nil now, but for what it’s worth that’s the way Jari had the AlertYesNo sample code :)

**Comment by jwink75** [comment]
I believe I have VS Code set up correctly on my MacBook, and I have enabled Sync Settings so that when I install it on my Windows computer it should theoretically be set up the same. The only errors VS Code is showing on the harp script now are in the window_pos_x and y globals (two errors total), having to do with window position saving, which I don't think I'm getting right... But would like to go ahead and merge and fix later, especially as I turn my attention to other things like the bug fixes I just put in the staff_rename script.

@Nick-Mazuk, @rpatters1, OK to merge and close this PR?

**Comment by jwink75** [comment]
Oops... I did not mean to commit that myself :P

**Comment by rpatters1** [comment]
Hey @jwink75 I may have messed this pull request up, based on a comment I'm seeing right above this one. But I am now seeing some more serious lint errors on this script than undefined globals. For example, it is complaining that Line 150:

```lua
                new_pedals[i] = harpstrings[i]
```

is assigning a string to a number, which is certainly how it looks.

**Comment by jwink75** [comment]
I will try to take a look sometime this weekend. Sent from my iPhoneOn Jan 28, 2023, at 7:14 AM, rpatters1 ***@***.***> wrote:﻿
Hey @jwink75 I may have messed this pull request up, based on a comment I'm seeing right above this one. But I am now seeing some more serious lint errors on this script than undefined globals. For example, it is complaining that Line 150:
                new_pedals[i] = harpstrings[i]
is assigning a string to a number, which is certainly how it looks.

**Comment by rpatters1** [comment]
Never mind. I think the problem was that I was looking at code based on an old branch of the code. It's back to just the `window_pos_x/y` warnings.

BTW: these would be easy to fix. You probably just need to add at the top:

```lua
window_pos_x = nil
window_pos_y = nil
```

But an even better solution would be to convert the dialog to `FCXCustomLuaWindow` using the `mixin` library. You could delete a lot of code then.

**Comment by rpatters1** [comment]
Hmm, when I open the harp_pedal_wizard script in VS Code it spits out more lint errors, including line 150 above that looks wrong. Anyway, if you could give it a glance that would be great. Lines 150 and 272 are the ones that look weird.

**Pull request merged**
