### PR TITLE
Update notes_tie.lua

### PR DESCRIPTION
**Pull request by cv-on-hub**
Fixing more plugindef() hiccups.

### CODE REVIEW

**Comment by cv-on-hub** [comment]
The only weird thing (now!) is I keep getting messages like the attached after each submission ..
unhappy_github

**Comment by Nick-Mazuk** [comment]
Oh, hmm…

It seems like the GitHub actions to build and deploy everything to the site are also running on your fork. Because of that, they're breaking (which is a good thing). However, they shouldn't be running on your fork.

Things seem to be running fine in the main repository, so it's not an issue as far as breaking the actual site.

Since it may be a few weeks since I'm able to really debug this, perhaps you can turn off notifications on your fork file an issue here to keep track of this?

Either way, this PR looks good to me.

**Comment by rpatters1** [comment]
I get those too. You can ignore them on your fork.

**Comment by cv-on-hub** [comment]
Great news all. I'll turn off the warnings.

**Pull request merged**
