### PR TITLE
Three new staff explode scripts

### PR DESCRIPTION
**Pull request by cv-on-hub**
Submitting three new staff_explode scripts based on a template provided by Nick Mazuk. 

I'm not sure if I'm doing the right thing here so please let me know if I need to handle GitHub Desktop and Visual Studio Code differently. I think I've created my own local fork of the repository, and these submissions from that fork should remain benign until approved for use in the master repository.

### CODE REVIEW

**Review by Nick-Mazuk — COMMENTED** [review]
Hey Carl, thanks for taking the time to try and tackle Git and GitHub!

Overall, looks great. You've definitely created a local version of the repository, and submitted a pull request correctly. And you've definitely not messed anything up (and even if you did, I can fix it).

I made two tiny comments that should be quick an easy to fix. To fix them, all you need to do is the following:

1. In your local version of the repo on your computer, edit the files like normal.
2. Create a new commit with the changes.
3. Push the changes to GitHub (the same way you did before).

The PR will automatically update with the new changes and I'll automatically get notified. I'll then approve this PR and merge it into the `master` branch!

Let me know if you have any questions. Feel free to ask here on GitHub or on Facebook.

**Comment by cv-on-hub** [comment]
Very glad to hear that it worked Nick! I hadn’t read through configuration.lua, but it’s purpose seemed perfectly obvious, I just didn’t think to update the config pointer for each file. Will make the changes and submit new request.

I can now bring some of my other scripts into the repository. Are there any you think are particularly useful?
http://carlvine.com/lua/

Carl

**Review by Nick-Mazuk — APPROVED** [review]

**Comment by cv-on-hub** [comment]
Many thanks Nick. The process wasn’t as gruelling as I had expected. Will add more in due course. Some of my larger scripts need major surgery to begin to approach FinaleLua style clarity.

Carl

**Comment by Nick-Mazuk** [comment]
Glad it wasn't as difficult as you expected!

If you'd like any help with Git in the future, feel free to ask.

Same with your larger scripts. You can create a "draft" pull request to get feedback early before it's ready to be merged. Then, when you're satisfied with it, you can set the pull request as "not draft" so we know it's good to merge.

**Pull request merged**
