### PR TITLE
Update general_library.lua

### PR DESCRIPTION
**Pull request by cv-on-hub**
library.simple_input() didn't work. Here's a fix.

### CODE REVIEW

**Comment by jwink75** [comment]
Thanks Carl! I've been struggling the last few days to fix JetStream, which uses a similar dialog... Can't wait to see how you fixed it!

On 12/6/2023 1:03:38 PM, Carl Vine ***@***.***> wrote:
library.simple_input() didn't work. Here's a fix.
You can view, comment on, or merge this pull request online at:
  https://github.com/finale-lua/lua-scripts/pull/610 [https://github.com/finale-lua/lua-scripts/pull/610]
Commit Summary
* e02070e [https://github.com/finale-lua/lua-scripts/pull/610/commits/e02070eb1ba66a230351b1ab9c767cd4aacc75d2] Update general_library.lua
File Changes
(1 file [https://github.com/finale-lua/lua-scripts/pull/610/files])
* M src/library/general_library.lua [https://github.com/finale-lua/lua-scripts/pull/610/files#diff-ca92f2967fe48a516123919b227d2245d8fd931773de6e8d14e60ce5d63b75b5] (14)
Patch Links:
* https://github.com/finale-lua/lua-scripts/pull/610.patch [https://github.com/finale-lua/lua-scripts/pull/610.patch]
* https://github.com/finale-lua/lua-scripts/pull/610.diff [https://github.com/finale-lua/lua-scripts/pull/610.diff]

**Comment by jwink75** [comment]
I find that sort of thing helpful  if I want to modify things later on. They didn't actually used to be commented out, that was something Carl added... though of course it didn't DO anything before either. Anyway, my vote would be to leave it in, though I conceded that if this is just being used in the library there is no real purpose to it.

-Jake

On 12/6/2023 1:16:49 PM, rpatters1 ***@***.***> wrote:
Is there a reason to keep the commented lines of code? (The callback)?

**Comment by rpatters1** [comment]
Generally speaking, most advice-givers think it's better to delete unused code than to comment it out. It runs counter to many programmers' instincts (including mine until a few years ago). But the problem is that commented code goes bad, and the longer it stays there the harder it is to delete it. I think you should delete it.

**Comment by cv-on-hub** [comment]
> [Here is a good article](https://methodpoet.com/commented-out-code/) on why not to comment

Yes - soundly argued. Revision, including optional "default value" field follows.

**Pull request merged**
