### PR TITLE
Update measure_span.lua

### PR DESCRIPTION
**Pull request by cv-on-hub**
Finally squashed a long-term gremlin of smartshapes failing to affix properly to newly inserted measures on `join` span. (I think). Minor code fixes.

### CODE REVIEW

**Comment by rpatters1** [comment]
What's the status of this? you've added several changes since you created the PR. Is it set now?

**Comment by cv-on-hub** [comment]
> What's the status of this?

Initially I needed to fix some serious inadequacies. Those are now stable but  I keep discovering expression types that don't shift correctly, so it might be best to leave it for a couple of days. I won't update again here until I've done everything I can. Hopefully the repo `update` system will be back working by then!

**Comment by cv-on-hub** [comment]
Trial method six is the charm. Mid-measure tempo markings will now reposition with adequate stability. New version is ready for absorption.

**Comment by cv-on-hub** [comment]
This script won't be updated again for the foreseeable future, and the sum of the submissions here correct substantial bugs in the version provided on `dist`.

**Pull request merged**
