### PR TITLE
Update notehead.lua

### PR DESCRIPTION
**Pull request by cv-on-hub**
Added layer filtering to the change_shape() method.

But on reflection, would layer filtering be more useful at FCNoteEntry level, and not FCNote? In which case create two new methods accepting those inputs? Thoughts?

### CODE REVIEW

**Comment by rpatters1** [comment]
How are you imagining this will be called? If it inside an `eachentrysaved` loop, you can filter the layer in `eachentrysaved`.

**Comment by cv-on-hub** [comment]
> you can filter the layer in `eachentrysaved`

That was my quandary. Are there other reasonable instances where `note` or `entry` might objects arise for which the layer isn't predetermined? And separately, are `notehead.change_shape_entry()` and `notehead.change_shape_region()` useful additions to the library?

**Comment by rpatters1** [comment]
The is no reason to add library functions for the sake of adding library functions. There needs to be a clear and present problem it is solving. These functions you propose would not be added to `notehead`. The entry one would be added to `note_entry`. We could discuss where to add a region based one.

My question is specific. Why are we adding a layer filter at all at any level, when layer filters already exist in `eachentrysaved`? Is that not enough for what you are doing?

**Comment by cv-on-hub** [comment]
> Is that not enough for what you are doing?

`eachentrysaved` is fine for what I need. I was asking whether some other circumstance I haven't imagined could sensibly use layer filtering.

**Pull request closed without merging**
