### PR TITLE
Create delete_selective.lua

### PR DESCRIPTION
**Pull request by cv-on-hub**
This script replaces 11 independent "deletion" scripts that I've used for years. Not sure how useful it will be to others, depending on their workflow preferences.

### CODE REVIEW

**Review by Nick-Mazuk — APPROVED** [review]
Yes please! I currently have a KM macro to do this through the Finale UI. But a script is so much faster. Thanks!

**Comment by cv-on-hub** [comment]
I started making these scripts in direct response to your SuperUser KM macro-palette system. Not sure if I should include MIDI data (note and/or continuous).

**Comment by rpatters1** [comment]
You should be using `eachbackwards` with articulations as well. Right now you are failing to delete one or more if there are multiple articulations. However, this is being masked by the fact that you are resetting the articulation flag.

**Comment by rpatters1** [comment]
Some other issues:

- I was going to tell you you should be calling `DeleteEverything` (with loaded center shapes) instead of `DeleteData`, but Finale itself seems to be cleaning up for you (better than `DeleteEverything` would). This is weird magic to me, so I have asked my contact at MakeMusic to confirm it.
- You expression deletion code is leaving the `FCMeasure.ExpressionFlag` set, even if you delete all the expressions. My recommendation is to do a fresh call of `CreateExpressions` and reset it if the returned collection is empty.
- Your `measure_expression` code should use `eachbackwards`.

**Pull request merged**
