### PR TITLE
Add jetstream

### PR DESCRIPTION
**Pull request by Nick-Mazuk**
This PR adds the JetStream files as discussed in #259.

The `CODEOWNERS` file ensures that any changes to the JetStream files (`jetstream.lua` and `jetstream_config.lua`) are approved by either CJ or Jacob.

Additionally, as discussed in #259, the standard code review process will not apply to this PR, but any future changes to the JetStream files will go through normal code review.

Either @jwink75 or @CJGarciaMusic should be the one to merge this PR.

### CODE REVIEW

**Comment by rpatters1** [comment]
I don't know where this stands with regards to committing it. I am going to use the conversation to discuss a possible change that would avoid the annoying dialog box.

I am thinking about adding a startup option to RGP Lua that would allow a script to run at startup. This script would run a coroutine that wakes up periodically and looks for a temp file that contains the command to execute. The only issue would be if the Jet Stream code can write the temp file.

Also, @Nick-Mazuk I am wondering if the jetstream project should not be under its own repository inside the finale-lua organization. It could include the libraries by means of a submodule inclusion of this repo. If that is impractical, then could we at least separate it in `src/jetstream`?

**Comment by jwink75** [comment]
I’ll respond more fully later on, but I’m curious how the user is supposed to select what function to execute without the dialog box? And for what it’s worth: I actually LOVE being able to run things directly from the dialog box… “annoying” is subjective :)Sent from my iPhoneOn Feb 13, 2023, at 7:05 AM, rpatters1 ***@***.***> wrote:﻿
I don't know where this stands with regards to committing it. I am going to use the conversation to discuss a possible change that would avoid the annoying dialog box.
I am thinking about adding a startup option to RGP Lua that would allow a script to run at startup. This script would run a coroutine that wakes up periodically and looks for a temp file that contains the command to execute. The only issue would be if the Jet Stream code can write the temp file.
Also, @Nick-Mazuk I am wondering if the jetstream project should not be under its own repository inside the finale-lua organization. It could include the libraries by means of a submodule inclusion of this repo. If that is impractical, then could we at least separate it in src/jetstream?

**Comment by rpatters1** [comment]
I literally just watched one of @Nick-Mazuk's videos where the dialog box was listed as a negative. I suppose I was reacting to that. I'm assuming you must know the codes for some of the functions by heart. Is this a likely scenario for the average user?

**Comment by rpatters1** [comment]
To answer your question, the Jet Stream controller generates a code, correct? I'm guessing it propagates the code into the dialog box by invoking the menu option and filling it with text. Is this an Applescript or something?

What the JetStream could do instead is write the code to a temp file. Then the coroutine running in Finale could pick it up and either execute the function directly or invoke the menu option which would read and then delete the text file. Or if you want to get fancy it might be possible to use luasocket, but that would require some programming in the JetStream controller that might not be feasible.

**Comment by jwink75** [comment]
That is accurate, but incomplete :)1) On Windows, hitting a button on the Stream Deck calls up a centralized EXE running AutoIT code. It tells the EXE what to do, which is sometimes call up the JetStream script and enter a code.2) On Mac, The Stream Deck runs ad hoc AppleScript code to do the same. I recently had to replace all of the buttons using the OBA Script plug-in since the Apple Script plug in was no longer supported. I lost the better part of a weekend to that… 3) Mac users also have the option of running JetStream through Keyboard Maestro. Again, that calls up the script from the menu and enters a code.4) In either platform, you can enter commands manually, even multiple commands (for example, entering “p < f” calls up commands for entering a starting p dynamic, adding a hairpin, adding a final f dynamic, then aligning them). This has actually become my preferred method of invoking several common tasks in Finale, including setting time and key signatures, clefs, barlines, entering dynamics and articulations, and calling up some other plugins like my harp pedal wizard, slur wizard, and staff renaming script.I’m not willing to give up #4. I don’t know AppleScript at all: that was all CJ’s work, and he has been too busy for JetStream for about a year. He also doesn’t own a Mac anymore! I may be able to figure out a Keyboard Maestro solution, and almost assuredly could figure it out with AutoIT, but especially not being sure about how to tackle the AppleScript it’s a pretty low priority, certainly lower than something like trying to get better performance out of my dynamic positioning routine.As for the repository situation… Right now I’m still using the GitHub that CJ set up. I’ve had enough issues with trying to sync Git Hub and manage pull requests and having multiple copies of things in different places on multiple computers that unless someone is going to slowly walk me through how to manage two GitHub locations for the same project, I’m not going to move it over. However, if CJ agrees we could move all of the JetStream stuff over and have this be the only location. He has indicated that this Spring he may have more time to be involved!Sent from my iPhoneOn Feb 13, 2023, at 8:26 AM, rpatters1 ***@***.***> wrote:﻿
To answer your question, the Jet Stream controller generates a code, correct? I'm guessing it propagates the code into the dialog box by invoking the menu option and filling it with text. Is this an Applescript or something?
What the JetStream could do instead is write the code to a temp file. Then the coroutine running in Finale could pick it up and either execute the function directly or invoke the menu option which would read and then delete the text file. Or if you want to get fancy it might be possible to use luasocket, but that would require some programming in the JetStream controller that might not be feasible.

**Comment by rpatters1** [comment]
I am going to close this pull request. I would encourage @jwink75 to move the Jet Stream repo to the Finale Lua organization as an alternative.

**Pull request closed without merging**
