### PR TITLE
Update layer_clear_selective.lua

### PR DESCRIPTION
**Pull request by cv-on-hub**
All of this hoo-hah so that the MODAL dialog retains its screen position in RGP 0.64+. Still stable on earlier RGP versions, and not using mixin until it is fully stabilised.

### CODE REVIEW

**Comment by rpatters1** [comment]
If you want it to retain position always, use `RegisterHandleCloseWindow` instead of `RegisterHandleOkButtonPressed`. Right now it only remembers the window position if the user presses `OK`.

**Comment by cv-on-hub** [comment]
Good to know, but I was thinking specifically that a "cancel" would NOT retain window position.

**Comment by rpatters1** [comment]
Not how I would do it, but it's your baby.

**Comment by rpatters1** [comment]
`RegisterHandleCloseWindow` also handles the case of it being closed with the close button (upper left small button).

**Comment by cv-on-hub** [comment]
OK you've convinced me!

**Comment by Nick-Mazuk** [comment]
I'll let Robert review and approve this one as he's much more familiar with the dialogs.

**Review by Nick-Mazuk — APPROVED** [review]
Looks good to me.

**Pull request merged**
