### PR TITLE
Back to straight text for VS Code instructions

### PR DESCRIPTION
**Pull request by asherber**
This reverts commit 638b9efc7c051e5ba30f5a0e0fe16ff0e82865d0.
This reverts commit 7a16d6b1d4f4512919cb1952f6eacfca046eda5e.

### CODE REVIEW

**Review by Nick-Mazuk — APPROVED** [review]
Approving. Will merge and check the build to ensure things do actually work. Will roll back if not.

**Comment by Nick-Mazuk** [comment]
Looks good!

https://www.finalelua.com/docs/rgp-lua/development-environment

**Comment by asherber** [comment]
Thanks @Nick-Mazuk and @rpatters1 -- appreciate your help in fixing this!

**Comment by rpatters1** [comment]
I'm going to get this working on my system this afternoon. Once I do that, I will add vscode-debuggee.lua to the list of scripts the RGP Lua ignores in folder searches.

**Pull request merged**
