### PR TITLE
Create hairpin_creator_configuration.lua

### PR DESCRIPTION
**Pull request by cv-on-hub**
New script to configure `hairpin_creator` without using modifier key invocation. This has proven distinctly more convenient for a KM-freak than using the modifier key invocation. Configuration alone was provided with the original version of the script as an extra menu item whether you wanted it or not. Isolated like this it's only there if you want it.

### CODE REVIEW

**Comment by rpatters1** [comment]
It should be an AdditionalMenuItem. Do not duplicate this code. In my setup, it will end up as a menu item either way, so just let it be a menu it.

**Review by rpatters1 — COMMENTED** [review]
The "Configuration" menu option should have "..." to indicate it opens a dialog:

```
Configuration...
```

**Comment by cv-on-hub** [comment]
> The "Configuration" menu option should have "..." to indicate it opens a dialog:

Of course. Will do.

**Review by rpatters1 — APPROVED** [review]
lgtm

**Pull request merged**
